version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-database
    environment:
      POSTGRES_DB: mabase
      POSTGRES_USER: utilisateur
      POSTGRES_PASSWORD: motdepasse123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
    driver: local